fixed build:lib error and reduced build time

diff --git a/build-lib b/build-lib
--- a/build-lib
+++ b/build-lib
@@ -1,6 +1,20 @@
 #!/bin/bash
-./init
-yarn build:lib
+set -e
+
+## install dep and devDep
+if [ ! -d node_modules ]; then
+  ./install-lib-dep
+fi
+if [ ! -d node_modules/typescript ]; then
+  npm i typescript
+fi
+
+## build
+./gen-index
+npm run build:lib
+
+## clean up devDep
 rm -rf node_modules
 ./install-lib-dep
+
 echo "done."
